import { SequenceTrip, PayRates, SubscribedCalendar, PersonalCalendarEvent } from "../types";

/**
 * Formats a Date object or YYYY-MM-DD + HHMM string into UTC iCal format (YYYYMMDDTHHMMSSZ or YYYYMMDD)
 */
function formatIcsDateTime(dateStr: string, timeStr?: string): string {
  const cleanDate = dateStr.replace(/-/g, "");
  if (!timeStr) return cleanDate;

  const cleanTime = timeStr.replace(/[^0-9]/g, "").padStart(4, "0");
  return `${cleanDate}T${cleanTime}00`;
}

/**
 * Generates RFC 5545 compliant .ics iCalendar file text for the user's active roster sequences
 */
export function generateRosterIcs(sequences: SequenceTrip[], payRates?: PayRates): string {
  const nowUtc = new Date().toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
  
  const ics = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//CrewSchedule Pro//Airline Roster Calendar//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "X-WR-CALNAME:CrewSchedule Pro Roster",
    "X-WR-TIMEZONE:UTC",
    "X-WR-CALDESC:Live Flight Attendant & Pilot Schedule Sync",
  ];

  sequences.forEach((seq) => {
    const uid = `seq-${seq.id}-${seq.startDate}@crewschedule-pro`;
    const firstDp = seq.dutyPeriods ? seq.dutyPeriods[0] : null;
    const lastDp = seq.dutyPeriods ? seq.dutyPeriods[seq.dutyPeriods.length - 1] : null;
    
    const repTime = firstDp ? firstDp.reportTime : "0600";
    const relTime = lastDp ? lastDp.releaseTime : "1800";

    const dtStart = formatIcsDateTime(seq.startDate, repTime);
    const dtEnd = formatIcsDateTime(seq.endDate, relTime);

    const flightSummary = seq.dutyPeriods
      ? seq.dutyPeriods.flatMap((d) => d.legs.map((f) => `${f.flightNumber} (${f.depAirport}->${f.arrAirport})`)).join(", ")
      : "";

    const layoverSummary = seq.dutyPeriods
      ? seq.dutyPeriods.map((d, i) => d.layoverCity ? `Day ${i + 1} Layover: ${d.layoverCity}` : null).filter(Boolean).join(" | ")
      : "";

    const creditHrs = (seq.totalCreditMinutes / 60).toFixed(1);
    const blockHrs = (seq.totalBlockMinutes / 60).toFixed(1);

    const summary = `✈️ Sequence #${seq.sequenceNumber} [${seq.base || "ORD"}] (${creditHrs}h Credit)`;
    const description = [
      `Sequence: #${seq.sequenceNumber}`,
      `Base: ${seq.base || "ORD"}`,
      `Credit Hours: ${creditHrs} hrs`,
      `Block Hours: ${blockHrs} hrs`,
      `Flights: ${flightSummary}`,
      layoverSummary ? `Layovers: ${layoverSummary}` : `Type: 1-Day Turn`,
      `Report: ${repTime} | Release: ${relTime}`,
      `Generated by CrewSchedule Pro`,
    ].join("\\n");

    const location = seq.layoverCities?.length ? seq.layoverCities.join(", ") : `${seq.base || "ORD"} Base`;

    ics.push(
      "BEGIN:VEVENT",
      `UID:${uid}`,
      `DTSTAMP:${nowUtc}`,
      `DTSTART:${dtStart}`,
      `DTEND:${dtEnd}`,
      `SUMMARY:${summary}`,
      `DESCRIPTION:${description}`,
      `LOCATION:${location}`,
      "STATUS:CONFIRMED",
      "TRANSP:OPAQUE",
      "END:VEVENT"
    );
  });

  ics.push("END:VCALENDAR");
  return ics.join("\r\n");
}

/**
 * Triggers browser download of .ics calendar file
 */
export function downloadRosterIcsFile(sequences: SequenceTrip[], payRates?: PayRates) {
  const icsText = generateRosterIcs(sequences, payRates);
  const blob = new Blob([icsText], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", `CrewSchedule_Pro_Roster_${new Date().toISOString().slice(0, 10)}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generates live WebCAL and HTTPS subscription feed URLs
 */
export function generateSubscriptionUrls(token: string = "user-pilot-773") {
  const origin = typeof window !== "undefined" ? window.location.origin : "https://crewschedule-pro.app";
  const httpUrl = `${origin}/api/calendar/subscribe?token=${token}`;
  const webcalUrl = httpUrl.replace(/^https?:/, "webcal:");
  return { httpUrl, webcalUrl };
}

/**
 * Fetches a remote iCal feed (.ics / webcal:// / https://) by URL
 * Handles webcal:// to https:// conversion and CORS proxy fallback
 */
/**
 * Fetches a remote iCal feed (.ics / webcal:// / https://) by URL
 * Handles webcal:// to https:// conversion and multi-proxy fallbacks for iCloud & Google feeds
 */
export async function fetchRemoteIcsFeed(rawUrl: string): Promise<string> {
  let url = rawUrl.trim();
  if (url.startsWith("webcal://")) {
    url = url.replace("webcal://", "https://");
  } else if (url.startsWith("webcals://")) {
    url = url.replace("webcals://", "https://");
  } else if (!url.startsWith("http://") && !url.startsWith("https://")) {
    url = `https://${url}`;
  }

  // Strategy 0: Electron Native IPC Fetch (bypasses CORS completely in desktop app)
  if (typeof window !== "undefined" && (window as any).electronAPI?.fetchRemoteUrl) {
    try {
      const nativeRes = await (window as any).electronAPI.fetchRemoteUrl(url);
      if (nativeRes && nativeRes.success && nativeRes.text && nativeRes.text.includes("BEGIN:VCALENDAR")) {
        return nativeRes.text;
      }
    } catch (e) {
      console.warn("Electron native fetch notice, trying browser fallbacks...", e);
    }
  }

  const fetchCandidates = [
    url,
    `https://corsproxy.io/?${encodeURIComponent(url)}`,
    `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`,
    `https://thingproxy.freeboard.io/fetch/${url}`,
    `https://api.codetabs.com/v1/proxy?quest=${encodeURIComponent(url)}`,
  ];

  for (const candidate of fetchCandidates) {
    try {
      const res = await fetch(candidate, { mode: "cors" });
      if (res.ok) {
        const text = await res.text();
        if (text && text.includes("BEGIN:VCALENDAR")) {
          return text;
        }
      }
    } catch (err) {
      console.warn(`Fetch candidate [${candidate.substring(0, 45)}...] failed, trying next...`, err);
    }
  }

  throw new Error("Could not fetch valid iCal calendar feed from URL. Please verify link is public or shared.");
}

/**
 * Parses raw .ics iCalendar text into PersonalCalendarEvent array for overlaying external events
 */
export function parseIcsText(icsContent: string, calendarId: string, color: string = "purple"): PersonalCalendarEvent[] {
  const events: PersonalCalendarEvent[] = [];
  
  // Unfold folded lines (lines starting with space or tab continuation)
  const unfolded = icsContent.replace(/\r?\n[ \t]/g, "");
  const lines = unfolded.split(/\r?\n/);
  
  let inEvent = false;
  let currentEvent: {
    title?: string;
    startDate?: string;
    endDate?: string;
    startTime?: string;
    endTime?: string;
    location?: string;
    notes?: string;
    rrule?: string;
  } = {};

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    
    if (line === "BEGIN:VEVENT") {
      inEvent = true;
      currentEvent = {};
    } else if (line === "END:VEVENT") {
      if (inEvent && currentEvent.startDate) {
        const eventTitle = currentEvent.title?.trim() || "Personal Calendar Event";
        const baseStart = currentEvent.startDate;
        const baseEnd = currentEvent.endDate || baseStart;

        // Base single event instance
        events.push({
          id: `evt-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
          calendarId,
          title: eventTitle,
          startDate: baseStart,
          endDate: baseEnd,
          startTime: currentEvent.startTime,
          endTime: currentEvent.endTime,
          location: currentEvent.location,
          notes: currentEvent.notes,
          color,
        });

        // Expand RRULE recurring events (e.g. FREQ=WEEKLY, FREQ=DAILY, FREQ=MONTHLY)
        if (currentEvent.rrule) {
          const rruleStr = currentEvent.rrule.toUpperCase();
          const isWeekly = rruleStr.includes("FREQ=WEEKLY");
          const isDaily = rruleStr.includes("FREQ=DAILY");
          const isMonthly = rruleStr.includes("FREQ=MONTHLY");

          if (isWeekly || isDaily || isMonthly) {
            const [sYear, sMonth, sDay] = baseStart.split("-").map(Number);
            const [eYear, eMonth, eDay] = baseEnd.split("-").map(Number);
            const durationMs = new Date(eYear, eMonth - 1, eDay).getTime() - new Date(sYear, sMonth - 1, sDay).getTime();

            const occurrences = isDaily ? 30 : isWeekly ? 12 : 3;
            for (let step = 1; step <= occurrences; step++) {
              const nextStart = new Date(sYear, sMonth - 1, sDay);
              if (isDaily) nextStart.setDate(nextStart.getDate() + step);
              else if (isWeekly) nextStart.setDate(nextStart.getDate() + step * 7);
              else if (isMonthly) nextStart.setMonth(nextStart.getMonth() + step);

              const nextEnd = new Date(nextStart.getTime() + durationMs);

              const startIso = `${nextStart.getFullYear()}-${String(nextStart.getMonth() + 1).padStart(2, "0")}-${String(nextStart.getDate()).padStart(2, "0")}`;
              const endIso = `${nextEnd.getFullYear()}-${String(nextEnd.getMonth() + 1).padStart(2, "0")}-${String(nextEnd.getDate()).padStart(2, "0")}`;

              events.push({
                id: `evt-${Date.now()}-${step}-${Math.random().toString(36).substring(2, 7)}`,
                calendarId,
                title: eventTitle,
                startDate: startIso,
                endDate: endIso,
                startTime: currentEvent.startTime,
                endTime: currentEvent.endTime,
                location: currentEvent.location,
                notes: currentEvent.notes,
                color,
              });
            }
          }
        }
      }
      inEvent = false;
    } else if (inEvent) {
      const colonIdx = line.indexOf(":");
      if (colonIdx === -1) continue;

      const keyPart = line.slice(0, colonIdx).toUpperCase();
      const val = line.slice(colonIdx + 1).trim();

      if (keyPart.startsWith("SUMMARY")) {
        currentEvent.title = val.replace(/\\,/g, ",").replace(/\\;/g, ";").replace(/\\n/g, " ");
      } else if (keyPart.startsWith("LOCATION")) {
        currentEvent.location = val.replace(/\\,/g, ",").replace(/\\n/g, " ");
      } else if (keyPart.startsWith("DESCRIPTION")) {
        currentEvent.notes = val.replace(/\\n/g, " ");
      } else if (keyPart.startsWith("RRULE")) {
        currentEvent.rrule = val;
      } else if (keyPart.startsWith("DTSTART")) {
        // Handle DTSTART;TZID=...:20260813T140000 or 20260813
        const cleanVal = val.replace(/[^0-9T]/g, "");
        const datePart = cleanVal.slice(0, 8); // YYYYMMDD
        if (datePart.length === 8) {
          currentEvent.startDate = `${datePart.slice(0, 4)}-${datePart.slice(4, 6)}-${datePart.slice(6, 8)}`;
          if (cleanVal.includes("T") && cleanVal.length >= 13) {
            const timePart = cleanVal.split("T")[1].slice(0, 4);
            currentEvent.startTime = `${timePart.slice(0, 2)}:${timePart.slice(2, 4)}`;
          }
        }
      } else if (keyPart.startsWith("DTEND")) {
        const cleanVal = val.replace(/[^0-9T]/g, "");
        const datePart = cleanVal.slice(0, 8);
        if (datePart.length === 8) {
          let endY = datePart.slice(0, 4);
          let endM = datePart.slice(4, 6);
          let endD = datePart.slice(6, 8);

          const isDateOnly = !val.includes("T") || val.includes("VALUE=DATE");
          if (isDateOnly) {
            const d = new Date(parseInt(endY, 10), parseInt(endM, 10) - 1, parseInt(endD, 10));
            d.setDate(d.getDate() - 1);
            endY = String(d.getFullYear());
            endM = String(d.getMonth() + 1).padStart(2, "0");
            endD = String(d.getDate()).padStart(2, "0");
          }

          currentEvent.endDate = `${endY}-${endM}-${endD}`;
          if (cleanVal.includes("T") && cleanVal.length >= 13) {
            const timePart = cleanVal.split("T")[1].slice(0, 4);
            currentEvent.endTime = `${timePart.slice(0, 2)}:${timePart.slice(2, 4)}`;
          }
        }
      }
    }
  }

  return events;
}
