// Auto-generated real schedule & logbook data from Austin Pryor's live HI1, HI2, and HSS files
import { SequenceTrip, LogbookEntry, VacationPeriod } from "../types";

export const USER_LIVE_VACATIONS: VacationPeriod[] = [
  {
    id: "vac-2026-08-01-2026-08-05",
    startDate: "2026-08-01",
    endDate: "2026-08-05",
    code: "VC",
    description: "Scheduled Vacation Block (01AUG26 to 05AUG26)",
  }
];

export const USER_LIVE_SEQUENCES: SequenceTrip[] = [
  // AUG 2026 - SEQ 14731 (RA - Regular Assignment Revision)
  {
    id: "seq-14731-20260813",
    rank: "CA",
    sequenceNumber: "14731",
    startDate: "2026-08-13",
    endDate: "2026-08-16",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 718, // 11.58h
    totalCreditMinutes: 754, // 12.57h (12h 34m)
    expTafbHours: 65.22,
    statusTag: "RA",
    isDropped: false,
    layoverCities: ["AVP", "ORD", "CLE"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0830",
        releaseTime: "1648",
        dutyMinutes: 498,
        payCreditMinutes: 498, // 8.16h
        payStatusCode: "1",
        addCode: "RA",
        layoverCity: "AVP",
        legs: [
          {
            flightNumber: "AA3602",
            depAirport: "ORD",
            arrAirport: "AVP",
            depTime: "0915",
            arrTime: "1205",
            blockMinutes: 110,
            groundMinutes: 45,
            equipment: "E75E",
            tailNumber: "N360AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA4140",
            depAirport: "AVP",
            arrAirport: "ORD",
            depTime: "1250",
            arrTime: "1350",
            blockMinutes: 120,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N414AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "1100",
        releaseTime: "1539",
        dutyMinutes: 279,
        payCreditMinutes: 159, // 2.39h
        payStatusCode: "1",
        addCode: "RA",
        layoverCity: "ORD",
        legs: [
          {
            flightNumber: "AA3362",
            depAirport: "ORD",
            arrAirport: "ORD",
            depTime: "1145",
            arrTime: "1508",
            blockMinutes: 143,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N336AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "1315",
        releaseTime: "1644",
        dutyMinutes: 209,
        payCreditMinutes: 89, // 1.29h
        payStatusCode: "1",
        addCode: "RA",
        layoverCity: "CLE",
        legs: [
          {
            flightNumber: "AA3749",
            depAirport: "ORD",
            arrAirport: "CLE",
            depTime: "1400",
            arrTime: "1619",
            blockMinutes: 79,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N374AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 3,
        reportTime: "0715",
        releaseTime: "1046",
        dutyMinutes: 211,
        payCreditMinutes: 91, // 1.31h
        payStatusCode: "1",
        addCode: "RA",
        layoverCity: "",
        legs: [
          {
            flightNumber: "AA3356",
            depAirport: "CLE",
            arrAirport: "ORD",
            depTime: "0800",
            arrTime: "0831",
            blockMinutes: 91,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N335AA",
            isDeadhead: false,
          },
        ],
      },
    ],
  },

  // AUG 2026 - SEQ 14962 (Scheduled 4-Day Trip)
  {
    id: "seq-14962-20260820",
    rank: "CA",
    sequenceNumber: "14962",
    startDate: "2026-08-20",
    endDate: "2026-08-23",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 1349, // 22.29h
    totalCreditMinutes: 1349, // 22.29h
    expTafbHours: 73.44,
    statusTag: "SKD",
    isDropped: false,
    layoverCities: ["RIC", "FSM", "MAF"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0845",
        releaseTime: "1728",
        dutyMinutes: 523,
        payCreditMinutes: 403, // 6.43h
        payStatusCode: "1",
        layoverCity: "RIC",
        legs: [
          {
            flightNumber: "AA4145",
            depAirport: "ORD",
            arrAirport: "RIC",
            depTime: "0930",
            arrTime: "1230",
            blockMinutes: 120,
            groundMinutes: 45,
            equipment: "E75E",
            tailNumber: "N414AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3811",
            depAirport: "RIC",
            arrAirport: "ORD",
            depTime: "1315",
            arrTime: "1630",
            blockMinutes: 130,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N381AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "1015",
        releaseTime: "1647",
        dutyMinutes: 392,
        payCreditMinutes: 272, // 4.32h
        payStatusCode: "1",
        layoverCity: "FSM",
        legs: [
          {
            flightNumber: "AA3778",
            depAirport: "ORD",
            arrAirport: "FSM",
            depTime: "1100",
            arrTime: "1305",
            blockMinutes: 125,
            groundMinutes: 45,
            equipment: "E75E",
            tailNumber: "N377AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3859",
            depAirport: "FSM",
            arrAirport: "ORD",
            depTime: "1350",
            arrTime: "1604",
            blockMinutes: 134,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N385AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "0645",
        releaseTime: "1534",
        dutyMinutes: 529,
        payCreditMinutes: 289, // 4.49h
        payStatusCode: "1",
        layoverCity: "MAF",
        legs: [
          {
            flightNumber: "AA4179",
            depAirport: "ORD",
            arrAirport: "MAF",
            depTime: "0730",
            arrTime: "1000",
            blockMinutes: 150,
            groundMinutes: 35,
            equipment: "E75E",
            tailNumber: "N417AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3873",
            depAirport: "MAF",
            arrAirport: "DFW",
            depTime: "1035",
            arrTime: "1145",
            blockMinutes: 70,
            groundMinutes: 35,
            equipment: "E75E",
            tailNumber: "N387AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3512",
            depAirport: "DFW",
            arrAirport: "MAF",
            depTime: "1220",
            arrTime: "1330",
            blockMinutes: 70,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N351AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 3,
        reportTime: "0530",
        releaseTime: "1555",
        dutyMinutes: 625,
        payCreditMinutes: 385, // 6.25h
        payStatusCode: "1",
        layoverCity: "",
        legs: [
          {
            flightNumber: "AA3352",
            depAirport: "MAF",
            arrAirport: "ORD",
            depTime: "0615",
            arrTime: "0855",
            blockMinutes: 160,
            groundMinutes: 40,
            equipment: "E75E",
            tailNumber: "N335AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3689",
            depAirport: "ORD",
            arrAirport: "ORD",
            depTime: "0935",
            arrTime: "1115",
            blockMinutes: 100,
            groundMinutes: 35,
            equipment: "E75E",
            tailNumber: "N368AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3573",
            depAirport: "ORD",
            arrAirport: "ORD",
            depTime: "1150",
            arrTime: "1340",
            blockMinutes: 110,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N357AA",
            isDeadhead: false,
          },
        ],
      },
    ],
  },

  // AUG 2026 - SEQ 15101 (Scheduled 4-Day Trip)
  {
    id: "seq-15101-20260827",
    rank: "CA",
    sequenceNumber: "15101",
    startDate: "2026-08-27",
    endDate: "2026-08-30",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 986, // 16.26h
    totalCreditMinutes: 986, // 16.26h
    expTafbHours: 70.35,
    statusTag: "SKD",
    isDropped: false,
    layoverCities: ["SPI", "MLI", "GSO"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "1230",
        releaseTime: "1918",
        dutyMinutes: 408,
        payCreditMinutes: 288, // 4.48h
        payStatusCode: "1",
        layoverCity: "SPI",
        legs: [
          {
            flightNumber: "AA3626",
            depAirport: "ORD",
            arrAirport: "SPI",
            depTime: "1315",
            arrTime: "1415",
            blockMinutes: 60,
            groundMinutes: 30,
            equipment: "E75E",
            tailNumber: "N362AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3594",
            depAirport: "SPI",
            arrAirport: "ORD",
            depTime: "1445",
            arrTime: "1545",
            blockMinutes: 60,
            groundMinutes: 35,
            equipment: "E75E",
            tailNumber: "N359AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3771",
            depAirport: "ORD",
            arrAirport: "SPI",
            depTime: "1620",
            arrTime: "1720",
            blockMinutes: 60,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N377AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "1406",
        releaseTime: "1826",
        dutyMinutes: 260,
        payCreditMinutes: 149, // 2.29h
        payStatusCode: "1",
        layoverCity: "MLI",
        legs: [
          {
            flightNumber: "AA4330",
            depAirport: "SPI",
            arrAirport: "ORD",
            depTime: "1451",
            arrTime: "1609",
            blockMinutes: 78,
            groundMinutes: 51,
            equipment: "E75E",
            tailNumber: "N433AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3559",
            depAirport: "ORD",
            arrAirport: "MLI",
            depTime: "1700",
            arrTime: "1811",
            blockMinutes: 71,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N355AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "0515",
        releaseTime: "1301",
        dutyMinutes: 466,
        payCreditMinutes: 200, // 3.20h
        payStatusCode: "1",
        layoverCity: "GSO",
        legs: [
          {
            flightNumber: "AA3708",
            depAirport: "MLI",
            arrAirport: "ORD",
            depTime: "0600",
            arrTime: "0719",
            blockMinutes: 79,
            groundMinutes: 146,
            equipment: "E75E",
            tailNumber: "N370AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA4144",
            depAirport: "ORD",
            arrAirport: "GSO",
            depTime: "0945",
            arrTime: "1246",
            blockMinutes: 121,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N414AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 3,
        reportTime: "0704",
        releaseTime: "1458",
        dutyMinutes: 474,
        payCreditMinutes: 349, // 5.49h
        payStatusCode: "1",
        layoverCity: "",
        legs: [
          {
            flightNumber: "AA3673",
            depAirport: "GSO",
            arrAirport: "ORD",
            depTime: "0749",
            arrTime: "0910",
            blockMinutes: 141,
            groundMinutes: 95,
            equipment: "E75E",
            tailNumber: "N367AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3552",
            depAirport: "ORD",
            arrAirport: "ORD",
            depTime: "1045",
            arrTime: "1443",
            blockMinutes: 208,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N355AA",
            isDeadhead: false,
          },
        ],
      },
    ],
  },

  // AUG 2026 - SEQ 15156 (Dropped for Vacation)
  {
    id: "seq-15156-20260806-drp",
    rank: "CA",
    sequenceNumber: "15156",
    startDate: "2026-08-06",
    endDate: "2026-08-09",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 934, // 15.57h
    totalCreditMinutes: 934, // 15.57h
    statusTag: "DROP",
    isDropped: true,
    layoverCities: [],
    dutyPeriods: [],
  },
];

export const USER_LOGBOOK_ENTRIES: LogbookEntry[] = [
  {
    id: "log-20260813-3602",
    date: "2026-08-13",
    flightNumber: "AA3602",
    tailNumber: "N360AA",
    aircraftType: "E75E",
    depAirport: "ORD",
    arrAirport: "AVP",
    outTime: "0915",
    inTime: "1205",
    blockMinutes: 110,
    nightMinutes: 0,
    instrumentMinutes: 20,
    crossCountryMinutes: 110,
    picMinutes: 110,
    sicMinutes: 0,
    dualReceivedMinutes: 0,
    landingsDay: 1,
    landingsNight: 0,
    approaches: 1,
    remarks: "Regular assignment (RA) leg 1",
    isAutoFilled: true,
    sourceSequenceNumber: "14731",
    createdAt: "2026-08-15T19:24:00.000Z",
  },
];
