// Auto-generated real schedule & logbook data from Austin Pryor's live HI1, HI2, and HSS files
import { SequenceTrip, LogbookEntry, VacationPeriod } from "../types";

export const USER_LIVE_VACATIONS: VacationPeriod[] = [
  {
    id: "vac-2026-08-01-2026-08-07",
    startDate: "2026-08-01",
    endDate: "2026-08-07",
    code: "VC",
    description: "Scheduled Vacation Block (01AUG26 to 07AUG26)",
    creditHours: 35.0,
  }
];

export const USER_LIVE_SEQUENCES: SequenceTrip[] = [
  // ==========================================
  // JULY 2026 SEQUENCES (Full HSS Trip Detail)
  // ==========================================

  // JUL 2026 - SEQ 21649 (Trade Pickup - 3-Day Trip)
  {
    id: "seq-21649-20260706",
    rank: "CA",
    sequenceNumber: "21649",
    startDate: "2026-07-06",
    endDate: "2026-07-08",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 751, // 12.51h
    totalCreditMinutes: 1040, // 17.34h (17h 20m)
    expTafbHours: 52.55,
    statusTag: "TT",
    colorTag: "amber",
    isDropped: false,
    layoverCities: ["EVV", "BIL"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0845",
        releaseTime: "1845",
        dutyMinutes: 600,
        payCreditMinutes: 388,
        layoverCity: "EVV",
        layoverHotelInfo: "DoubleTree by Hilton Evansville (812-423-5002)",
        legs: [
          { flightNumber: "AA3453", depAirport: "ORD", arrAirport: "PVD", depTime: "0926", arrTime: "1232", blockMinutes: 126, equipment: "E75E", tailNumber: "N345AA", isDeadhead: false },
          { flightNumber: "AA3453", depAirport: "PVD", arrAirport: "ORD", depTime: "1337", arrTime: "1517", blockMinutes: 160, equipment: "E75E", tailNumber: "N345AA", isDeadhead: false },
          { flightNumber: "AA3511", depAirport: "ORD", arrAirport: "EVV", depTime: "1731", arrTime: "1845", blockMinutes: 74, equipment: "E75E", tailNumber: "N351AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "0612",
        releaseTime: "1228",
        dutyMinutes: 376,
        payCreditMinutes: 307,
        layoverCity: "BIL",
        layoverHotelInfo: "Northern Hotel Billings (406-867-6767)",
        legs: [
          { flightNumber: "AA3707", depAirport: "EVV", arrAirport: "ORD", depTime: "0657", arrTime: "0827", blockMinutes: 90, equipment: "E75E", tailNumber: "N370AA", isDeadhead: false },
          { flightNumber: "AA3428", depAirport: "ORD", arrAirport: "BIL", depTime: "0958", arrTime: "1143", blockMinutes: 165, equipment: "E75E", tailNumber: "N342AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "0500",
        releaseTime: "1400",
        dutyMinutes: 540,
        payCreditMinutes: 335,
        layoverCity: "",
        legs: [
          { flightNumber: "AA3746", depAirport: "BIL", arrAirport: "ORD", depTime: "0545", arrTime: "0945", blockMinutes: 180, equipment: "E75E", tailNumber: "N374AA", isDeadhead: false },
          { flightNumber: "AA3330", depAirport: "ORD", arrAirport: "ORD", depTime: "1115", arrTime: "1351", blockMinutes: 156, equipment: "E75E", tailNumber: "N333AA", isDeadhead: true },
        ],
      },
    ],
  },

  // JUL 2026 - SEQ 17352 (Dropped / Traded for 21649)
  {
    id: "seq-17352-20260706-drp",
    rank: "CA",
    sequenceNumber: "17352",
    startDate: "2026-07-06",
    endDate: "2026-07-08",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 841,
    totalCreditMinutes: 841,
    statusTag: "DROP",
    colorTag: "rose",
    isDropped: true,
    dropReason: "Traded for High-Credit Sequence #21649",
    layoverCities: ["CAE", "CMH"],
    dutyPeriods: [],
  },

  // JUL 2026 - SEQ 18080 (RA - Regular Assignment 4-Day Trip)
  {
    id: "seq-18080-20260711",
    rank: "CA",
    sequenceNumber: "18080",
    startDate: "2026-07-11",
    endDate: "2026-07-14",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 786, // 13.06h
    totalCreditMinutes: 937, // 15.37h
    expTafbHours: 77.19,
    statusTag: "RA",
    colorTag: "sky",
    isDropped: false,
    layoverCities: ["MEM", "BMI", "DFW"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "1620",
        releaseTime: "0011",
        dutyMinutes: 471,
        payCreditMinutes: 317,
        layoverCity: "MEM",
        layoverHotelInfo: "The Westin Memphis Beale Street (901-334-5900)",
        legs: [
          { flightNumber: "AA3383", depAirport: "ORD", arrAirport: "BNA", depTime: "1702", arrTime: "1837", blockMinutes: 95, equipment: "E75E", tailNumber: "N338AA", isDeadhead: false },
          { flightNumber: "AA3383", depAirport: "BNA", arrAirport: "ORD", depTime: "1925", arrTime: "2115", blockMinutes: 110, equipment: "E75E", tailNumber: "N338AA", isDeadhead: false },
          { flightNumber: "AA3945", depAirport: "ORD", arrAirport: "MEM", depTime: "2226", arrTime: "0011", blockMinutes: 105, equipment: "E75E", tailNumber: "N394AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "1745",
        releaseTime: "0240",
        dutyMinutes: 535,
        payCreditMinutes: 264,
        layoverCity: "BMI",
        layoverHotelInfo: "Bloomington-Normal Marriott (309-862-9000)",
        legs: [
          { flightNumber: "AA3677", depAirport: "MEM", arrAirport: "DFW", depTime: "2137", arrTime: "2325", blockMinutes: 108, equipment: "E75E", tailNumber: "N367AA", isDeadhead: false },
          { flightNumber: "AA4254", depAirport: "DFW", arrAirport: "BMI", depTime: "0004", arrTime: "0240", blockMinutes: 156, equipment: "E75E", tailNumber: "N425AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "1545",
        releaseTime: "2011",
        dutyMinutes: 266,
        payCreditMinutes: 138,
        layoverCity: "DFW",
        layoverHotelInfo: "Hyatt Regency DFW Airport (972-453-1234)",
        legs: [
          { flightNumber: "AA3434", depAirport: "BMI", arrAirport: "DFW", depTime: "1809", arrTime: "2011", blockMinutes: 122, equipment: "E75E", tailNumber: "N343AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 3,
        reportTime: "1603",
        releaseTime: "2124",
        dutyMinutes: 321,
        payCreditMinutes: 203,
        layoverCity: "",
        legs: [
          { flightNumber: "AA3803", depAirport: "DFW", arrAirport: "SGF", depTime: "1703", arrTime: "1823", blockMinutes: 80, equipment: "E75E", tailNumber: "N380AA", isDeadhead: true },
          { flightNumber: "AA3626", depAirport: "SGF", arrAirport: "ORD", depTime: "1954", arrTime: "2124", blockMinutes: 90, equipment: "E75E", tailNumber: "N362AA", isDeadhead: false },
        ],
      },
    ],
  },

  // JUL 2026 - SEQ 17475 (Dropped / Replaced by 18080)
  {
    id: "seq-17475-20260711-drp",
    rank: "CA",
    sequenceNumber: "17475",
    startDate: "2026-07-11",
    endDate: "2026-07-14",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 1093,
    totalCreditMinutes: 1093,
    statusTag: "DROP",
    colorTag: "rose",
    isDropped: true,
    dropReason: "Off Option (OO) — Replaced by Regular Assignment #18080",
    layoverCities: ["BHM", "MHT", "AVP"],
    dutyPeriods: [],
  },

  // JUL 2026 - SEQ 21514 (OT - Open Time Turn)
  {
    id: "seq-21514-20260715",
    rank: "CA",
    sequenceNumber: "21514",
    startDate: "2026-07-15",
    endDate: "2026-07-15",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 262, // 4.22h
    totalCreditMinutes: 309, // 5.09h
    expTafbHours: 6.15,
    statusTag: "OT",
    colorTag: "amber",
    isOvertime: true,
    isDropped: false,
    layoverCities: [],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0915",
        releaseTime: "1515",
        dutyMinutes: 360,
        payCreditMinutes: 309,
        layoverCity: "",
        legs: [
          { flightNumber: "AA3862", depAirport: "ORD", arrAirport: "HHH", depTime: "1001", arrTime: "1302", blockMinutes: 121, equipment: "E75E", tailNumber: "N386AA", isDeadhead: false },
          { flightNumber: "AA3862", depAirport: "HHH", arrAirport: "ORD", depTime: "1354", arrTime: "1515", blockMinutes: 141, equipment: "E75E", tailNumber: "N386AA", isDeadhead: false },
        ],
      },
    ],
  },

  // JUL 2026 - SEQ 21614 (RA / OT - Regular Assignment Turn)
  {
    id: "seq-21614-20260717",
    rank: "CA",
    sequenceNumber: "21614",
    startDate: "2026-07-17",
    endDate: "2026-07-17",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 304, // 5.04h
    totalCreditMinutes: 447, // 7.27h
    expTafbHours: 10.29,
    statusTag: "RA",
    colorTag: "amber",
    isOvertime: true,
    isDropped: false,
    layoverCities: [],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "1247",
        releaseTime: "2335",
        dutyMinutes: 648,
        payCreditMinutes: 447,
        layoverCity: "",
        legs: [
          { flightNumber: "AA3712", depAirport: "ORD", arrAirport: "MQT", depTime: "1322", arrTime: "1556", blockMinutes: 94, equipment: "E75E", tailNumber: "N371AA", isDeadhead: true },
          { flightNumber: "AA3712", depAirport: "MQT", arrAirport: "ORD", depTime: "1750", arrTime: "1820", blockMinutes: 90, equipment: "E75E", tailNumber: "N371AA", isDeadhead: false },
          { flightNumber: "AA3827", depAirport: "ORD", arrAirport: "TUL", depTime: "1903", arrTime: "2047", blockMinutes: 104, equipment: "E75E", tailNumber: "N382AA", isDeadhead: false },
          { flightNumber: "AA3827", depAirport: "TUL", arrAirport: "ORD", depTime: "2111", arrTime: "2335", blockMinutes: 144, equipment: "E75E", tailNumber: "N382AA", isDeadhead: false },
        ],
      },
    ],
  },

  // JUL 2026 - SEQ 21596 (LB 25 Lock-In)
  {
    id: "seq-21596-20260718",
    rank: "CA",
    sequenceNumber: "21596",
    startDate: "2026-07-18",
    endDate: "2026-07-18",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 158,
    totalCreditMinutes: 158,
    statusTag: "LB",
    colorTag: "sky",
    isDropped: false,
    layoverCities: [],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0800",
        releaseTime: "1130",
        dutyMinutes: 210,
        payCreditMinutes: 158,
        layoverCity: "",
        legs: [
          { flightNumber: "AA4174", depAirport: "ORD", arrAirport: "ORD", depTime: "0845", arrTime: "1123", blockMinutes: 158, equipment: "E75E", tailNumber: "N417AA", isDeadhead: false },
        ],
      },
    ],
  },

  // JUL 2026 - SEQ 17495 (4-Day Scheduled Trip)
  {
    id: "seq-17495-20260718",
    rank: "CA",
    sequenceNumber: "17495",
    startDate: "2026-07-18",
    endDate: "2026-07-21",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 1046, // 17.26h
    totalCreditMinutes: 1043, // 17.23h
    expTafbHours: 74.07,
    statusTag: "SKD",
    colorTag: "sky",
    isDropped: false,
    layoverCities: ["SPI", "HPN", "YYZ"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "1215",
        releaseTime: "1424",
        dutyMinutes: 129,
        payCreditMinutes: 72,
        layoverCity: "SPI",
        layoverHotelInfo: "President Abraham Lincoln Springfield - A DoubleTree by Hilton (217-544-8800)",
        legs: [
          { flightNumber: "AA4330", depAirport: "ORD", arrAirport: "SPI", depTime: "1312", arrTime: "1424", blockMinutes: 72, equipment: "E75E", tailNumber: "N433AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "0515",
        releaseTime: "1531",
        dutyMinutes: 616,
        payCreditMinutes: 374,
        layoverCity: "HPN",
        layoverHotelInfo: "Sonesta White Plains Downtown (914-682-0050)",
        legs: [
          { flightNumber: "AA4328", depAirport: "SPI", arrAirport: "ORD", depTime: "0551", arrTime: "0705", blockMinutes: 74, equipment: "E75E", tailNumber: "N432AA", isDeadhead: false },
          { flightNumber: "AA3491", depAirport: "ORD", arrAirport: "CWA", depTime: "0804", arrTime: "0902", blockMinutes: 58, equipment: "E75E", tailNumber: "N349AA", isDeadhead: false },
          { flightNumber: "AA3491", depAirport: "CWA", arrAirport: "ORD", depTime: "0948", arrTime: "1106", blockMinutes: 78, equipment: "E75E", tailNumber: "N349AA", isDeadhead: false },
          { flightNumber: "AA4200", depAirport: "ORD", arrAirport: "HPN", depTime: "1236", arrTime: "1531", blockMinutes: 115, equipment: "E75E", tailNumber: "N420AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "0525",
        releaseTime: "1218",
        dutyMinutes: 413,
        payCreditMinutes: 237,
        layoverCity: "YYZ",
        layoverHotelInfo: "Toronto Airport Marriott Hotel (416-674-9400)",
        legs: [
          { flightNumber: "AA3496", depAirport: "HPN", arrAirport: "ORD", depTime: "0706", arrTime: "0826", blockMinutes: 140, equipment: "E75E", tailNumber: "N349AA", isDeadhead: false },
          { flightNumber: "AA3606", depAirport: "ORD", arrAirport: "YYZ", depTime: "0941", arrTime: "1218", blockMinutes: 97, equipment: "E75E", tailNumber: "N360AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 3,
        reportTime: "0532",
        releaseTime: "1407",
        dutyMinutes: 515,
        payCreditMinutes: 317,
        layoverCity: "",
        legs: [
          { flightNumber: "AA3524", depAirport: "YYZ", arrAirport: "ORD", depTime: "0717", arrTime: "0827", blockMinutes: 130, equipment: "E75E", tailNumber: "N352AA", isDeadhead: false },
          { flightNumber: "AA3498", depAirport: "ORD", arrAirport: "DTW", depTime: "1030", arrTime: "1304", blockMinutes: 94, equipment: "E75E", tailNumber: "N349AA", isDeadhead: false },
          { flightNumber: "AA3498", depAirport: "DTW", arrAirport: "ORD", depTime: "1334", arrTime: "1407", blockMinutes: 93, equipment: "E75E", tailNumber: "N349AA", isDeadhead: false },
        ],
      },
    ],
  },

  // JUL 2026 - SEQ 21566 (OT - Open Time Turn)
  {
    id: "seq-21566-20260723",
    rank: "CA",
    sequenceNumber: "21566",
    startDate: "2026-07-23",
    endDate: "2026-07-23",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 204, // 3.24h
    totalCreditMinutes: 218, // 3.58h
    expTafbHours: 5.28,
    statusTag: "OT",
    colorTag: "amber",
    isOvertime: true,
    isDropped: false,
    layoverCities: [],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "1351",
        releaseTime: "1836",
        dutyMinutes: 285,
        payCreditMinutes: 218,
        layoverCity: "",
        legs: [
          { flightNumber: "AA4151", depAirport: "ORD", arrAirport: "MHK", depTime: "1428", arrTime: "1606", blockMinutes: 98, equipment: "E75E", tailNumber: "N415AA", isDeadhead: false },
          { flightNumber: "AA4151", depAirport: "MHK", arrAirport: "ORD", depTime: "1650", arrTime: "1836", blockMinutes: 106, equipment: "E75E", tailNumber: "N415AA", isDeadhead: false },
        ],
      },
    ],
  },

  // JUL 2026 - SEQ 17333 (3-Day Scheduled / RA Trip)
  {
    id: "seq-17333-20260724",
    rank: "CA",
    sequenceNumber: "17333",
    startDate: "2026-07-24",
    endDate: "2026-07-26",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 813, // 13.33h
    totalCreditMinutes: 872, // 14.52h
    expTafbHours: 53.39,
    statusTag: "SKD",
    colorTag: "sky",
    isDropped: false,
    layoverCities: ["AVP", "MLI"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0715",
        releaseTime: "1738",
        dutyMinutes: 623,
        payCreditMinutes: 367,
        layoverCity: "AVP",
        layoverHotelInfo: "Mohegan Sun Pocono (570-831-2100)",
        legs: [
          { flightNumber: "AA3625", depAirport: "ORD", arrAirport: "LIT", depTime: "0757", arrTime: "0941", blockMinutes: 104, equipment: "E75E", tailNumber: "N362AA", isDeadhead: false },
          { flightNumber: "AA3625", depAirport: "LIT", arrAirport: "ORD", depTime: "1020", arrTime: "1220", blockMinutes: 120, equipment: "E75E", tailNumber: "N362AA", isDeadhead: false },
          { flightNumber: "AA3407", depAirport: "ORD", arrAirport: "AVP", depTime: "1454", arrTime: "1738", blockMinutes: 104, equipment: "E75E", tailNumber: "N340AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "0415",
        releaseTime: "1047",
        dutyMinutes: 392,
        payCreditMinutes: 224,
        layoverCity: "MLI",
        layoverHotelInfo: "Radisson On John Deere Commons-Moline (309-764-1000)",
        legs: [
          { flightNumber: "AA3587", depAirport: "AVP", arrAirport: "ORD", depTime: "0559", arrTime: "0710", blockMinutes: 131, equipment: "E75E", tailNumber: "N358AA", isDeadhead: false },
          { flightNumber: "AA3698", depAirport: "ORD", arrAirport: "MLI", depTime: "0942", arrTime: "1047", blockMinutes: 65, equipment: "E75E", tailNumber: "N369AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "0523",
        releaseTime: "1222",
        dutyMinutes: 419,
        payCreditMinutes: 301,
        layoverCity: "",
        legs: [
          { flightNumber: "AA3445", depAirport: "MLI", arrAirport: "ORD", depTime: "0558", arrTime: "0656", blockMinutes: 58, equipment: "E75E", tailNumber: "N344AA", isDeadhead: false },
          { flightNumber: "AA3439", depAirport: "ORD", arrAirport: "BNA", depTime: "0825", arrTime: "0949", blockMinutes: 84, equipment: "E75E", tailNumber: "N343AA", isDeadhead: false },
          { flightNumber: "AA3439", depAirport: "BNA", arrAirport: "ORD", depTime: "1043", arrTime: "1222", blockMinutes: 99, equipment: "E75E", tailNumber: "N343AA", isDeadhead: false },
        ],
      },
    ],
  },

  // JUL 2026 - SEQ 17894 (TT - 2-Day Trade Trip)
  {
    id: "seq-17894-20260727",
    rank: "CA",
    sequenceNumber: "17894",
    startDate: "2026-07-27",
    endDate: "2026-07-28",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 645, // 10.45h
    totalCreditMinutes: 645, // 10.45h
    expTafbHours: 24.15,
    statusTag: "TT",
    colorTag: "sky",
    isDropped: false,
    layoverCities: ["CAE"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "1421",
        releaseTime: "2319",
        dutyMinutes: 538,
        payCreditMinutes: 327,
        layoverCity: "CAE",
        layoverHotelInfo: "Courtyard Columbia Downtown at USC (803-799-7800)",
        legs: [
          { flightNumber: "AA3980", depAirport: "ORD", arrAirport: "DTW", depTime: "1506", arrTime: "1741", blockMinutes: 95, equipment: "E75E", tailNumber: "N398AA", isDeadhead: false },
          { flightNumber: "AA3980", depAirport: "DTW", arrAirport: "ORD", depTime: "1811", arrTime: "1858", blockMinutes: 107, equipment: "E75E", tailNumber: "N398AA", isDeadhead: false },
          { flightNumber: "AA4275", depAirport: "ORD", arrAirport: "CAE", depTime: "2014", arrTime: "2319", blockMinutes: 125, equipment: "E75E", tailNumber: "N427AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "1528",
        releaseTime: "1844",
        dutyMinutes: 196,
        payCreditMinutes: 151,
        layoverCity: "",
        legs: [
          { flightNumber: "AA4183", depAirport: "CAE", arrAirport: "ORD", depTime: "1713", arrTime: "1844", blockMinutes: 151, equipment: "E75E", tailNumber: "N418AA", isDeadhead: false },
        ],
      },
    ],
  },

  // JUL 2026 - SEQ 17270 (2-Day Scheduled Trip)
  {
    id: "seq-17270-20260730",
    rank: "CA",
    sequenceNumber: "17270",
    startDate: "2026-07-30",
    endDate: "2026-07-31",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 565, // 9.25h
    totalCreditMinutes: 565, // 9.25h
    expTafbHours: 29.20,
    statusTag: "SKD",
    colorTag: "sky",
    isDropped: false,
    layoverCities: ["SPI"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0606",
        releaseTime: "1424",
        dutyMinutes: 498,
        payCreditMinutes: 331,
        layoverCity: "SPI",
        layoverHotelInfo: "President Abraham Lincoln Springfield (217-544-8800)",
        legs: [
          { flightNumber: "AA3446", depAirport: "ORD", arrAirport: "BWI", depTime: "0651", arrTime: "0958", blockMinutes: 127, equipment: "E75E", tailNumber: "N344AA", isDeadhead: false },
          { flightNumber: "AA3446", depAirport: "BWI", arrAirport: "ORD", depTime: "1028", arrTime: "1143", blockMinutes: 135, equipment: "E75E", tailNumber: "N344AA", isDeadhead: false },
          { flightNumber: "AA4330", depAirport: "ORD", arrAirport: "SPI", depTime: "1315", arrTime: "1424", blockMinutes: 69, equipment: "E75E", tailNumber: "N433AA", isDeadhead: false },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "0515",
        releaseTime: "1130",
        dutyMinutes: 375,
        payCreditMinutes: 230,
        layoverCity: "",
        legs: [
          { flightNumber: "AA4328", depAirport: "SPI", arrAirport: "ORD", depTime: "0600", arrTime: "0718", blockMinutes: 78, equipment: "E75E", tailNumber: "N432AA", isDeadhead: false },
          { flightNumber: "AA3546", depAirport: "ORD", arrAirport: "GRB", depTime: "0805", arrTime: "0921", blockMinutes: 76, equipment: "E75E", tailNumber: "N354AA", isDeadhead: false },
          { flightNumber: "AA3546", depAirport: "GRB", arrAirport: "ORD", depTime: "0950", arrTime: "1105", blockMinutes: 75, equipment: "E75E", tailNumber: "N354AA", isDeadhead: false },
        ],
      },
    ],
  },

  // ==========================================
  // AUGUST 2026 SEQUENCES
  // ==========================================
  // AUG 2026 - SEQ 14731 (RA - Regular Assignment Revision)
  {
    id: "seq-14731-20260813",
    rank: "CA",
    sequenceNumber: "14731",
    startDate: "2026-08-13",
    endDate: "2026-08-16",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 718, // 11.58h
    totalCreditMinutes: 754, // 12.57h (12h 34m)
    expTafbHours: 65.22,
    statusTag: "RA",
    isDropped: false,
    layoverCities: ["AVP", "ORD", "CLE"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0830",
        releaseTime: "1648",
        dutyMinutes: 498,
        payCreditMinutes: 498, // 8.16h
        payStatusCode: "1",
        addCode: "RA",
        layoverCity: "AVP",
        legs: [
          {
            flightNumber: "AA3602",
            depAirport: "ORD",
            arrAirport: "AVP",
            depTime: "0915",
            arrTime: "1205",
            blockMinutes: 110,
            groundMinutes: 45,
            equipment: "E75E",
            tailNumber: "N360AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA4140",
            depAirport: "AVP",
            arrAirport: "ORD",
            depTime: "1250",
            arrTime: "1350",
            blockMinutes: 120,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N414AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "1100",
        releaseTime: "1539",
        dutyMinutes: 279,
        payCreditMinutes: 159, // 2.39h
        payStatusCode: "1",
        addCode: "RA",
        layoverCity: "ORD",
        legs: [
          {
            flightNumber: "AA3362",
            depAirport: "ORD",
            arrAirport: "ORD",
            depTime: "1145",
            arrTime: "1508",
            blockMinutes: 143,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N336AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "1315",
        releaseTime: "1644",
        dutyMinutes: 209,
        payCreditMinutes: 89, // 1.29h
        payStatusCode: "1",
        addCode: "RA",
        layoverCity: "CLE",
        legs: [
          {
            flightNumber: "AA3749",
            depAirport: "ORD",
            arrAirport: "CLE",
            depTime: "1400",
            arrTime: "1619",
            blockMinutes: 79,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N374AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 3,
        reportTime: "0715",
        releaseTime: "1046",
        dutyMinutes: 211,
        payCreditMinutes: 91, // 1.31h
        payStatusCode: "1",
        addCode: "RA",
        layoverCity: "",
        legs: [
          {
            flightNumber: "AA3356",
            depAirport: "CLE",
            arrAirport: "ORD",
            depTime: "0800",
            arrTime: "0831",
            blockMinutes: 91,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N335AA",
            isDeadhead: false,
          },
        ],
      },
    ],
  },

  // AUG 2026 - SEQ 14962 (Scheduled 4-Day Trip)
  {
    id: "seq-14962-20260820",
    rank: "CA",
    sequenceNumber: "14962",
    startDate: "2026-08-20",
    endDate: "2026-08-23",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 1349, // 22.29h
    totalCreditMinutes: 1349, // 22.29h
    expTafbHours: 73.44,
    statusTag: "SKD",
    isDropped: false,
    layoverCities: ["RIC", "FSM", "MAF"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0845",
        releaseTime: "1728",
        dutyMinutes: 523,
        payCreditMinutes: 403, // 6.43h
        payStatusCode: "1",
        layoverCity: "RIC",
        legs: [
          {
            flightNumber: "AA4145",
            depAirport: "ORD",
            arrAirport: "RIC",
            depTime: "0930",
            arrTime: "1230",
            blockMinutes: 120,
            groundMinutes: 45,
            equipment: "E75E",
            tailNumber: "N414AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3811",
            depAirport: "RIC",
            arrAirport: "ORD",
            depTime: "1315",
            arrTime: "1630",
            blockMinutes: 130,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N381AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "1015",
        releaseTime: "1647",
        dutyMinutes: 392,
        payCreditMinutes: 272, // 4.32h
        payStatusCode: "1",
        layoverCity: "FSM",
        legs: [
          {
            flightNumber: "AA3778",
            depAirport: "ORD",
            arrAirport: "FSM",
            depTime: "1100",
            arrTime: "1305",
            blockMinutes: 125,
            groundMinutes: 45,
            equipment: "E75E",
            tailNumber: "N377AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3859",
            depAirport: "FSM",
            arrAirport: "ORD",
            depTime: "1350",
            arrTime: "1604",
            blockMinutes: 134,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N385AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "0645",
        releaseTime: "1534",
        dutyMinutes: 529,
        payCreditMinutes: 289, // 4.49h
        payStatusCode: "1",
        layoverCity: "MAF",
        legs: [
          {
            flightNumber: "AA4179",
            depAirport: "ORD",
            arrAirport: "MAF",
            depTime: "0730",
            arrTime: "1000",
            blockMinutes: 150,
            groundMinutes: 35,
            equipment: "E75E",
            tailNumber: "N417AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3873",
            depAirport: "MAF",
            arrAirport: "DFW",
            depTime: "1035",
            arrTime: "1145",
            blockMinutes: 70,
            groundMinutes: 35,
            equipment: "E75E",
            tailNumber: "N387AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3512",
            depAirport: "DFW",
            arrAirport: "MAF",
            depTime: "1220",
            arrTime: "1330",
            blockMinutes: 70,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N351AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 3,
        reportTime: "0530",
        releaseTime: "1555",
        dutyMinutes: 625,
        payCreditMinutes: 385, // 6.25h
        payStatusCode: "1",
        layoverCity: "",
        legs: [
          {
            flightNumber: "AA3352",
            depAirport: "MAF",
            arrAirport: "ORD",
            depTime: "0615",
            arrTime: "0855",
            blockMinutes: 160,
            groundMinutes: 40,
            equipment: "E75E",
            tailNumber: "N335AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3689",
            depAirport: "ORD",
            arrAirport: "ORD",
            depTime: "0935",
            arrTime: "1115",
            blockMinutes: 100,
            groundMinutes: 35,
            equipment: "E75E",
            tailNumber: "N368AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3573",
            depAirport: "ORD",
            arrAirport: "ORD",
            depTime: "1150",
            arrTime: "1340",
            blockMinutes: 110,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N357AA",
            isDeadhead: false,
          },
        ],
      },
    ],
  },

  // AUG 2026 - SEQ 15101 (Scheduled 4-Day Trip)
  {
    id: "seq-15101-20260827",
    rank: "CA",
    sequenceNumber: "15101",
    startDate: "2026-08-27",
    endDate: "2026-08-30",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 986, // 16.26h
    totalCreditMinutes: 986, // 16.26h
    expTafbHours: 70.35,
    statusTag: "SKD",
    isDropped: false,
    layoverCities: ["SPI", "MLI", "GSO"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "1230",
        releaseTime: "1918",
        dutyMinutes: 408,
        payCreditMinutes: 288, // 4.48h
        payStatusCode: "1",
        layoverCity: "SPI",
        legs: [
          {
            flightNumber: "AA3626",
            depAirport: "ORD",
            arrAirport: "SPI",
            depTime: "1315",
            arrTime: "1415",
            blockMinutes: 60,
            groundMinutes: 30,
            equipment: "E75E",
            tailNumber: "N362AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3594",
            depAirport: "SPI",
            arrAirport: "ORD",
            depTime: "1445",
            arrTime: "1545",
            blockMinutes: 60,
            groundMinutes: 35,
            equipment: "E75E",
            tailNumber: "N359AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3771",
            depAirport: "ORD",
            arrAirport: "SPI",
            depTime: "1620",
            arrTime: "1720",
            blockMinutes: 60,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N377AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "1406",
        releaseTime: "1826",
        dutyMinutes: 260,
        payCreditMinutes: 149, // 2.29h
        payStatusCode: "1",
        layoverCity: "MLI",
        legs: [
          {
            flightNumber: "AA4330",
            depAirport: "SPI",
            arrAirport: "ORD",
            depTime: "1451",
            arrTime: "1609",
            blockMinutes: 78,
            groundMinutes: 51,
            equipment: "E75E",
            tailNumber: "N433AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3559",
            depAirport: "ORD",
            arrAirport: "MLI",
            depTime: "1700",
            arrTime: "1811",
            blockMinutes: 71,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N355AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "0515",
        releaseTime: "1301",
        dutyMinutes: 466,
        payCreditMinutes: 200, // 3.20h
        payStatusCode: "1",
        layoverCity: "GSO",
        legs: [
          {
            flightNumber: "AA3708",
            depAirport: "MLI",
            arrAirport: "ORD",
            depTime: "0600",
            arrTime: "0719",
            blockMinutes: 79,
            groundMinutes: 146,
            equipment: "E75E",
            tailNumber: "N370AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA4144",
            depAirport: "ORD",
            arrAirport: "GSO",
            depTime: "0945",
            arrTime: "1246",
            blockMinutes: 121,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N414AA",
            isDeadhead: false,
          },
        ],
      },
      {
        dayIndex: 3,
        reportTime: "0704",
        releaseTime: "1458",
        dutyMinutes: 474,
        payCreditMinutes: 349, // 5.49h
        payStatusCode: "1",
        layoverCity: "",
        legs: [
          {
            flightNumber: "AA3673",
            depAirport: "GSO",
            arrAirport: "ORD",
            depTime: "0749",
            arrTime: "0910",
            blockMinutes: 141,
            groundMinutes: 95,
            equipment: "E75E",
            tailNumber: "N367AA",
            isDeadhead: false,
          },
          {
            flightNumber: "AA3552",
            depAirport: "ORD",
            arrAirport: "ORD",
            depTime: "1045",
            arrTime: "1443",
            blockMinutes: 208,
            groundMinutes: 0,
            equipment: "E75E",
            tailNumber: "N355AA",
            isDeadhead: false,
          },
        ],
      },
    ],
  },

  // AUG 2026 - SEQ 15156 (Dropped for Vacation)
  {
    id: "seq-15156-20260806-drp",
    rank: "CA",
    sequenceNumber: "15156",
    startDate: "2026-08-06",
    endDate: "2026-08-09",
    base: "ORD",
    equipment: "E75E",
    totalBlockMinutes: 840,
    totalCreditMinutes: 1200,
    colorTag: "rose",
    statusTag: "DROP",
    isDropped: true,
    dropReason: "DTS Overlap — Touches Vacation Window (Aug 01 - Aug 07)",
    layoverCities: ["MSP", "DSM", "MSN"],
    dutyPeriods: [
      {
        dayIndex: 0,
        reportTime: "0800",
        releaseTime: "1530",
        dutyMinutes: 450,
        payCreditMinutes: 300,
        layoverCity: "MSP",
        legs: [
          { flightNumber: "AA4210", depAirport: "ORD", arrAirport: "MSP", depTime: "0845", arrTime: "1015", blockMinutes: 90, equipment: "E75E", isDeadhead: false },
          { flightNumber: "AA4211", depAirport: "MSP", arrAirport: "ORD", depTime: "1115", arrTime: "1245", blockMinutes: 90, equipment: "E75E", isDeadhead: false },
        ],
      },
      {
        dayIndex: 1,
        reportTime: "0830",
        releaseTime: "1600",
        dutyMinutes: 450,
        payCreditMinutes: 300,
        layoverCity: "DSM",
        legs: [
          { flightNumber: "AA3314", depAirport: "MSP", arrAirport: "DSM", depTime: "0915", arrTime: "1030", blockMinutes: 75, equipment: "E75E", isDeadhead: false },
          { flightNumber: "AA3315", depAirport: "DSM", arrAirport: "ORD", depTime: "1145", arrTime: "1300", blockMinutes: 75, equipment: "E75E", isDeadhead: false },
        ],
      },
      {
        dayIndex: 2,
        reportTime: "0900",
        releaseTime: "1630",
        dutyMinutes: 450,
        payCreditMinutes: 300,
        layoverCity: "MSN",
        legs: [
          { flightNumber: "AA4480", depAirport: "DSM", arrAirport: "MSN", depTime: "0945", arrTime: "1100", blockMinutes: 75, equipment: "E75E", isDeadhead: false },
          { flightNumber: "AA4481", depAirport: "MSN", arrAirport: "ORD", depTime: "1215", arrTime: "1330", blockMinutes: 75, equipment: "E75E", isDeadhead: false },
        ],
      },
      {
        dayIndex: 3,
        reportTime: "0830",
        releaseTime: "1400",
        dutyMinutes: 330,
        payCreditMinutes: 300,
        layoverCity: "",
        legs: [
          { flightNumber: "AA3890", depAirport: "MSN", arrAirport: "ORD", depTime: "0915", arrTime: "1030", blockMinutes: 75, equipment: "E75E", isDeadhead: false },
        ],
      },
    ],
  },
];

export const USER_LOGBOOK_ENTRIES: LogbookEntry[] = [
  {
    id: "log-20260813-3602",
    date: "2026-08-13",
    flightNumber: "AA3602",
    tailNumber: "N360AA",
    aircraftType: "E75E",
    depAirport: "ORD",
    arrAirport: "AVP",
    outTime: "0915",
    inTime: "1205",
    blockMinutes: 110,
    nightMinutes: 0,
    instrumentMinutes: 20,
    crossCountryMinutes: 110,
    picMinutes: 110,
    sicMinutes: 0,
    dualReceivedMinutes: 0,
    landingsDay: 1,
    landingsNight: 0,
    approaches: 1,
    remarks: "Regular assignment (RA) leg 1",
    isAutoFilled: true,
    sourceSequenceNumber: "14731",
    createdAt: "2026-08-15T19:24:00.000Z",
  },
];
